travis:
  secure:
    BINSTAR_TOKEN: rMA5NfqhDC1vTspyh/RGd6uHYDMb61TRnhXjw+QHJ+PDU+z+8dVJSC9KbvZTVjEps4NBi0BIalveQhaheEEllCSuf9cK6q0x6HyEwPYKfOgWwKqzxMFO4tmiiCHpopAZvrT+VyQ9YuX8YMr9YRFegvKswx5kotWoEV1A9yOUc7m/l/zv+hkZCpiD/e+9fgXers109/Io2PUcJ/paecsYzOuFZwkEqahzMwDdyAzaA4zYk7KlD651xjqyfCqLZVkP6jRBuEC9RUGLSiOfN1DZNDBjW7EUBtXWunNM8l2Y4oGrsweb58r97sic+X0jucVFrHH8stVbrHJWoczCovyTyGwg5uBXGR1NuqMORhE3miuz8lkoNzfYvYnTxNNp2mzRJyLwojw+YYF3PmjYVcqVq2OqwMKwRa5cyvxIoTRrU21s68RluuzBsxYCPuFhWqppE6zRvncTqSDTGDRFAMM2Rj7IJO90w03wQpXmXaCOweJGmWDmQEr2l2LnIx0iHZWeJc+FGE+K8EuZg5XC+gEvNy3nLp1ubnkfZSetB/GAyHXkSbOS0xVXAATAxJaC71gROPT6Fosz4LlscD0KYlGoT1Nh77NLyvLCwMBynoIdmP/6ShMH1b4nudx3GmEBKYIhMofOQsMODCSnt3iu69lqXcuDAStV447xDNBx4QEcOKU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
